export const reducerCases = {
    SET_INFO: 'SET_INFO',
    SET_FEATURED: 'SET_FEATURED',  
    SET_TOP_AIRING: 'SET_TOP_AIRING',
    SET_RECENT_EPISODE: 'SET_RECENT_EPISODE',
    SET_EPISODE: 'SET_EPISODE',
}